config/routes.rb
Rails.application.routes.draw do
  get 'events/index'
  devise_for :users, :controllers => {:registrations => "registrations", :sessions =>"sessions"}
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :images
  resources :recommendations
  resources :tags
  resources :favorites, except: [:new, :index, :show, :edit, :update]
  resources :comments, except: [:new, :index, :show, :edit, :update]

  get 'activity', to: 'events#index'
  get 'uploaded', to: 'images#uploaded'
  get 'trends', to: 'trends#index'
  get '/images/tag/:name', to: 'images#find'

  get :user_recommendations, controller: :recommendations
  get :useritem_recommendations, controller: :recommendations

  root 'images#index'

  mount ActionCable.server => '/cable'
end

app/views/application_partials/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success border-success text-success" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <i class="fa fa-thumbs-up"></i> <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-danger border-danger text-danger" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <i class="fa fa-thumbs-down"></i> <%= flash[:alert] %>
    </div>
<% end %>

app/views/application_partials/_footer.html.erb
<footer class="footer">
  <div class="container">
    <hr/>
    <span class="text-muted">Created in Oregon and Hosted on AWS</span>
  </div>
</footer>

app/views/application_partials/_menu.html.erb
<div class="d-none d-xl-block d-lg-block d-md-block">
    <ul class="nav top-nav nav-pills justify-content-center">
        <li class="nav-item <%= 'active' if params[:controller] == 'events' && params[:action] == 'index' %>">
            <a class="nav-link"
            href="/activity"><i class="fa fa-feed" aria-hidden="true"></i> Activity</a>
        </li>       
        <li class="nav-item <%= 'active' if params[:controller] == 'images' && params[:action] == 'index' && !request.query_string.present? %>">
            <a class="nav-link" href="/"><i class="fa fa-clock-o" aria-hidden="true"></i> Recent</a>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item <%= 'active' if params[:controller] == 'images' && params[:action] == 'index' && request.query_string.present? %>">
            <%= link_to '<i class="fa fa-upload"></i> My Uploads'.html_safe, images_path(:view => "user"), :class => 'nav-link'%>
        </li>
        <% end %>                
        <li class="nav-item <%= 'active' if params[:controller] == 'tags' && params[:action] == 'index' %>">
            <a class="nav-link"
            href="/tags"><i class="fa fa-tags" aria-hidden="true"></i> Tags</a>
        </li>
        <li class="nav-item <%= 'active' if params[:controller] == 'trends' && params[:action] == 'index'%>">
            <a class="nav-link" href="/trends"><i class="fa fa-line-chart" aria-hidden="true"></i> Trends</a>
        </li>
        <% if devise_controller? %>
        <li class="nav-item active">
            <a class="nav-link" href="#"><i class="fa fa-user" aria-hidden="true"></i> User</a>
        </li>
        <% end %>
        <% if params[:controller] == 'images' && params[:action] == 'show' %>
            <li class="nav-item active">
                <a class="nav-link" href="#"><i class="fa fa-image" aria-hidden="true"></i> Image</a>
            </li>
        <% end %>
        <% if params[:controller] == 'images' && params[:action] == 'find' %>
            <li class="nav-item active">
                <a class="nav-link" href="#"><i class="fa fa-search" aria-hidden="true"></i> Find</a>
            </li>
        <% end %>        
    </ul>
</div>

<div class="d-xl-none d-lg-none d-md-none">
    <ul class="nav top-nav nav-pills justify-content-center hidden-sm-up">
        <li class="nav-item <%= 'active' if params[:controller] == 'events' && params[:action] == 'index'%>">
            <a class="nav-link" href="/activity"><i class="fa fa-feed" aria-hidden="true"></i></a>
        </li>    
        <li class="nav-item <%= 'active' if params[:controller] == 'images' && params[:action] == 'index' && !request.query_string.present?%>">
            <a class="nav-link"
            href="/"><i class="fa fa-clock-o" aria-hidden="true"></i></a>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item <%= 'active' if params[:controller] == 'images' && params[:action] == 'index' && request.query_string.present? %>">
            <%= link_to '<i class="fa fa-upload"></i>'.html_safe, images_path(:view => "user"), :class => 'nav-link'%>
        </li>
        <% end %>            
        <li class="nav-item <%= 'active' if params[:controller] == 'tags' && params[:action] == 'index'%>">
            <a class="nav-link" href="/tags"><i class="fa fa-tags" aria-hidden="true"></i></a>
        </li>
        <li class="nav-item <%= 'active' if params[:controller] == 'trends' && params[:action] == 'index'%>">
            <a class="nav-link"
            href="/trends"><i class="fa fa-line-chart" aria-hidden="true"></i></a>
        </li>
        <% if devise_controller? %>
        <li class="nav-item active">
            <a class="nav-link"
            href="#"><i class="fa fa-user" aria-hidden="true"></i></a>
        </li>
        <% end %> 
        <% if params[:controller] == 'images' && params[:action] == 'show' %>
            <li class="nav-item active">
                <a class="nav-link" href="#"><i class="fa fa-image" aria-hidden="true"></i></a>
            </li>
        <% end %>  
        <% if params[:controller] == 'images' && params[:action] == 'find' %>
            <li class="nav-item active">
                <a class="nav-link" href="#"><i class="fa fa-search" aria-hidden="true"></i></a>
            </li>
        <% end %>                 
    </ul>
</div>

<% if user_signed_in? %>
    <div class="row">
    <div class="col-12">
            <%= link_to '<i class="fa fa-camera-retro" aria-hidden="true"></i> Upload Image'.html_safe, new_user_session_path,
                :class => "btn btn-dark pull-right", 'data-toggle' => 'modal', 'data-target' => '#uploadModal' %>    
    </div>
    </div>
<% end %>

app/views/application_partials/_navigation.html.erb
<nav class="navbar navbar-light navbar-expand-md fixed-top" style="background-color: #ffffff;">
    <%= link_to "<span>#{image_tag("logo.png", height: 45, border: 0)}</span>".html_safe, root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-navbar" aria-controls="main-navbar" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="main-navbar"> 

        <ul class="navbar-nav ml-auto d-none d-xl-block d-lg-block d-md-block">
            <% if !user_signed_in? %>           
                <li class="nav-item"><%= link_to '<i class="fa fa-user" aria-hidden="true"></i> Sign In'.html_safe, new_user_session_path,
                    :class => "btn btn-primary my-2 my-sm-0" %>
                </li>
            <% else %>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="user-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="fa-stack"><i class="fa fa-circle fa-stack-2x"></i><i class="fa fa-user fa-stack-1x fa-inverse"></i></span>
                        <%= current_user.username %>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="user-dropdown">
                    <%= link_to "My Profile".html_safe, edit_user_registration_path, :class => "dropdown-item" %>
                    <% if current_user.admin? %>
                        <%= link_to "Admin".html_safe, rails_admin_path, :class => "dropdown-item" %>
                    <% end %>
                    <%= link_to "Logout".html_safe, destroy_user_session_path, :class => "dropdown-item" , method: :delete %>
                    </div>
                </li>  
            <% end %>
        </ul>
  
        <ul class="navbar-nav d-xl-none d-lg-none d-md-none mr-auto ">
            <% if !user_signed_in? %>        
                <li class="nav-item">
                    <%= link_to 'Sign In'.html_safe, new_user_session_path,
                    :class => "nav-link" %>
                </li>
            <% else %>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#"" id="user-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= current_user.username %></a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="user-dropdown">
                    <%= link_to "My Profile".html_safe, edit_user_registration_path, :class => "dropdown-item" %>
                    <% if current_user.admin? %>
                        <%= link_to "Admin".html_safe, rails_admin_path, :class => "dropdown-item" %>
                    <% end %>
                    <%= link_to "Logout".html_safe, destroy_user_session_path, :class => "dropdown-item" , method: :delete %>
                    </div>
                </li>  
            <% end %>
        </ul>

    </div>
</nav>

app/views/application_partials/_search.html.erb
<div class="container mt-3">
    <form class="navbar-form navbar-left" action="#">
    <div class="input-group">
        <input type="text" class="form-control" placeholder="Search" name="search">
        <div class="input-group-btn">
        &nbsp;
        <button class="btn btn-outline-secondary" type="submit">
            <i class="fa fa-search"></i>
        </button>
        </div>
    </div>
    </form>
</div>

app/views/application_partials/_upload.html.erb
<div class="modal fade" id="uploadModal" tabindex="-1" role="dialog" aria-labelledby="uploadModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="uploadModalLabel">Upload Image</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_for Image.new do |f| %>
        <div class="modal-body text-center">
          <div class="row">
            <div class="col">
              <%= image_tag("upload.png", height: 100, width: 10, border: 0, :class => "image_to_upload img-thumbnail") %>
            </div>
            <div class="col">
              <h6>
              Select an Image to Upload
              </h6>
              <p>
              Currently only .jpg smaller than 5mb are supported.
              </p>
              <label class="custom-file-upload btn btn-dark btn-block">
                <%= f.file_field :image_image, accept: 'image/png,image/gif,image/jpeg' %>
                Select Image
              </label>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <%= f.button "Upload".html_safe, :class => "btn btn-primary", type: :submit, :disabled => true, data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Uploading ..."} %>
        </div>
      <% end %>
    </div>
  </div>
</div>