config/routes.rb
Rails.application.routes.draw do
  get 'events/index'
  devise_for :users, :controllers => {:registrations => "registrations", :sessions =>"sessions"}
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :images
  resources :recommendations
  resources :tags
  resources :favorites, except: [:new, :index, :show, :edit, :update]
  resources :comments, except: [:new, :index, :show, :edit, :update]

  get 'activity', to: 'events#index'
  get 'uploaded', to: 'images#uploaded'
  get 'trends', to: 'trends#index'
  get '/images/tag/:name', to: 'images#find'

  get :user_recommendations, controller: :recommendations
  get :useritem_recommendations, controller: :recommendations

  root 'images#index'

  mount ActionCable.server => '/cable'
end

app/models/image.rb
class Image < ApplicationRecord

  has_many :tags, dependent: :delete_all
  has_many :events, dependent: :delete_all
  has_many :favorites, dependent: :delete_all
  has_many :comments, dependent: :delete_all
  has_one_attached :image_image
  belongs_to :user

  after_create_commit :detect_labels, :log_create
  after_update_commit :log_update
  after_destroy_commit :log_destroy

  # Pagination Items Per Page
  self.per_page = 20
  
  private
  def detect_labels
    DetectLabelsJob.perform_async(self.id)
    DetectModerationLabelsJob.perform_async(self.id)
    DetectTextJob.perform_async(self.id)
    DetectCelebritiesJob.perform_async(self.id)
    DetectExifDataJob.perform_async(self.id)
  end

  private

  def log_create
    image_logger.info("Image created: User: #{self.user.username} Image: #{self.id} ")
  end

  def log_update
    image_logger.info("Image updated: User: #{self.user.username} Image: #{self.id} ")
  end

  def log_destroy
    image_logger.info("Image deleted: User: #{self.user.username} Image: #{self.id} ")
  end

  def image_logger
    @@image_logger ||= Logger.new("#{Rails.root}/log/application.log")
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:show, :index, :find]
  skip_before_action :verify_authenticity_token

  # GET /images
  # GET /images.json
  def index
    if request.query_parameters['view'] == 'user'
      image_logger.info("Loading all images for User: #{!current_user.nil? ? current_user.username : 'No User'} Page: #{!params[:page].nil? ? params[:page] : '1'}")
      @images = Image.where(user: current_user).order(created_at: :desc).paginate(page: params[:page])
      respond_to do |format|
      format.html
      format.js
      end
    elsif request.query_parameters['view'] == 'favorites'
      image_logger.info("Loading all images for User: #{!current_user.nil? ? current_user.username : 'No User'} Page: #{!params[:page].nil? ? params[:page] : '1'}")
      @images = Image.where(user: current_user).order(created_at: :desc).paginate(page: params[:page])
            
      respond_to do |format|
      format.html
      format.js
      end
    else
      image_logger.info("Loading all images for User: #{!current_user.nil? ? current_user.username : 'No User'} Page: #{!params[:page].nil? ? params[:page] : '1'}")
      @images = Image.order(created_at: :desc).paginate(page: params[:page])
      respond_to do |format|
      format.html
      format.js
      end
    end
  end

  # GET /images/id
  def show

    if current_user

      @category = Tag.where(image_id: @image.id).where("confidence > ?", 98.0).first

      if Favorite.where("user_id = ? AND image_id = ?", current_user.id, @image.id).count > 0
        @favorited = true
        @favorite = Favorite.find_by_user_id_and_image_id(current_user.id, @image.id)
      else
        @favorited = false
      end
    end

    image_logger.info("Showing details for Image: #{@image.id} User: #{!current_user.nil? ? current_user.username : 'No User'}")
  end

  def find
    image_logger.info("Loading images with Tag: #{params[:name]}")
    @images = Image.joins(:tags).where(tags: {name: params[:name]}).paginate(:page => params[:page])
    respond_to do |format|
     format.html
     format.js
    end
  end

  # POST /images
  # POST /images.json
  def create
    @image = current_user.images.new(image_params)
    image_logger.info("Image uploaded started: #{current_user.username}")

    respond_to do |format|
      if @image.save
        image_logger.info("Image upload successful: User #{current_user.username} Image: #{@image.id}")
        format.html { redirect_to @image, notice: 'Your image was successfully uploaded.' }
        format.json { render :show, status: :created, location: @image }
      else
        image_logger.error("Image upload failed: User #{current_user.username}")
        format.html { redirect_to root_url, alert: 'Unable to upload image.' }
        format.json { render json: @image, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        image_logger.info("Successfully updated Image: #{@image.id}")
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        image_logger.error("Error updating Image: #{@image}")
        format.html { redirect_to root_url, alert: 'Unable to update image.' }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    authorize! :delete, @image
    image_logger.info("Attempting to delete Image: #{@image.id}")
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_image
      @image = Image.find(params[:id])
    end

    def image_params
      params.require(:image).permit(:image_image)
    end

    def image_logger
      @@image_logger ||= Logger.new("#{Rails.root}/log/application.log")
    end

end

app/views/images/_image.html.erb
<div class="col-lg-3 col-md-3 col-xs-6">
  <figure class="figure">
    <!-- MODAL DISABLED <a href="#" data-toggle="modal" data-target="#modal-<%= image.id %>"> -->
    <a href="/images/<%= image.id %>">
      <%= image_tag image.image_image.variant(resize: "300x200"), :class => "img-fluid img-thumbnail" %>
    </a>
    <figcaption class="figure-caption text-center">
    </span>
    </figcaption>
  </figure>
</div>

<!-- Modal -->
<div class="modal fade" id="modal-<%= image.id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5>
          <span class="fa-stack fa-lg">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-user fa-stack-1x fa-inverse"></i>
          </span>
            <%= image.user.username %>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row" id='image'>
          <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
          <center>
            <figure class="figure">
              <%= image_tag image.image_image.variant(resize: "600x400"), :class => "img-fluid img-thumbnail" %>
            </figure>
          </center>
          </div>
          <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
            <table class="table text-center">
              <tr>
                <td><%= image.created_at.strftime("%m/%d/%Y") %> <%= image.created_at.strftime("%I:%M%p") %></td>
              </tr>
              <tr>
                <td>
                  <% if image.tags.count > 0 %>
                    <% image.tags.each do |tag| %>
                      <% if tag.source == "Rekognition - Detect Labels"%>
                        <%= link_to tag.name, "/images/tag/#{tag.name}", :title => "#{tag.name} - #{number_to_percentage(tag.confidence)}", :class => "badge badge-secondary" %>
                      <% end %>
                      <% if tag.source == "Rekognition - Detect Moderation Labels"%>
                        <%= link_to tag.name, "/images/tag/#{tag.name}", :title => "#{tag.name} - #{number_to_percentage(tag.confidence)}", :class => "badge badge-success" %>
                      <% end %>   
                       <% if tag.source == "Rekognition - Detect Text"%>
                        <%= link_to tag.name, "/images/tag/#{tag.name}", :title => "#{tag.name} - #{number_to_percentage(tag.confidence)}", :class => "badge badge-warning" %>
                      <% end %>
                      <% if tag.source == "Rekognition - Recognize Celebrities"%>
                        <%= link_to tag.name, "/images/tag/#{tag.name}", :title => "#{tag.name} - #{number_to_percentage(tag.confidence)}", :class => "badge badge-info" %>
                      <% end %>                                                             
                    <% end %>
                  <% else %>
                    <span class="badge badge-secondary">No Tags</span>
                  <% end %>
                </td>
              </tr>
              <tr>
                <td>
                  <center>Analyzed By</center>
                  <span class="badge badge-secondary">Rekognition - Detect Labels</span>
                  <span class="badge badge-success">Rekognition - Detect Moderation Labels</span>
                  <span class="badge badge-warning">Rekognition - Detect Text</span>
                  <span class="badge badge-info">Rekognition - Recognize Celebrities</span>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/images/_recommended.html.erb
<% if user_signed_in? %>
    <h5>Recommended Images</h5>
    <div class="row text-center text-lg-left" id='images'>
        <%= render @recommended %>
    </div>
    <hr/>
<% end %>

app/views/images/find.html.erb
<a href="javascript:" id="return-to-top"><i class="fa fa-chevron-up"></i></a>
<center><span class="badge badge-secondary"><%= params[:name] %></span></center>
<br/>
<% if Image.count == 0 %>
  <div class="card text-white bg-danger">
    <div class="card-body">
      <p class="card-text">No images to display, upload an image to get started!</p>
    </div>
  </div>
<% else %>
  <div class="row text-center text-lg-left" id='images'>
    <%= render @images %>
  </div>

  <%= will_paginate @images %>
<% end %>

app/views/images/find.js.erb
$('#images').append('<%= j render(@images) %>');
<% if @images.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@images) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/images/index.html.erb
<a href="javascript:" id="return-to-top"><i class="fa fa-chevron-up"></i></a>
<% if @images.count == 0 %>
  <div class="card text-white bg-danger">
    <div class="card-body">
      <p class="card-text">No images to display, upload an image to get started!</p>
    </div>
  </div>
<% else %>

  <!-- 
  <% if user_signed_in? %>
    <%= render_async user_recommendations_path do %>
      <i class='fa fa-spinner fa-spin'></i> Loading Recommendations ...
    <% end %>
  <% end %>
  -->

  <div class="row text-center text-lg-left" id='images'>  
    <%= render @images %>
  </div>

  <%= will_paginate @images %>
<% end %>

app/views/images/index.js.erb
$('#images').append('<%= j render(@images) %>');
<% if @images.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@images) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/images/show.html.erb
<div class="row">
  <div class="col-12">

    <span class="fa-stack fa-lg">
      <i class="fa fa-circle fa-stack-2x"></i>
      <i class="fa fa-user fa-stack-1x fa-inverse"></i>
    </span>
    <%= @image.user.username %>

    <%= link_to '<i class="fa fa-download"></i>'.html_safe, rails_blob_path(@image.image_image, disposition: "attachment"),
                :class => "btn btn-outline-secondary pull-right ml-2" %>
    <% if current_user && @image.user.id == current_user.id %>
      <%= link_to '<i class="fa fa-trash"></i>'.html_safe, image_path(@image), data: {:confirm => 'Are you sure?'}, :method => :delete, :class => "btn btn-outline-danger pull-right" %>
    <% end %>
  </div>
</div>

<hr/>

<div class="row" id='image'>
  <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
    <figure class="figure">
      <%= image_tag @image.image_image.variant(resize: "600x400"), :class => "img-fluid img-thumbnail" %>
    </figure>
        
    <% if current_user %>
      <% if @favorited == false %>
        <%= form_for Favorite.new do |f| %>
            <%= f.hidden_field :image_id, value: @image.id %>
            <%= f.hidden_field :user_id, value: current_user.id %></td>
            <%= f.button "<i class='fa fa-heart'></i> #{!@image.favorites.nil? ? @image.favorites.count : "0" }".html_safe, type: :submit, :class => "btn btn-outline-secondary pull-right" %>
        <% end %>
      <% else %>
        <%= link_to "<i class='fa fa-heart'> #{@image.favorites.count}</i>".html_safe, favorite_path(@favorite), :method => :delete, :class => "btn btn-outline-light pull-right", :style => "color: red;" %>
      <% end %>
    <% end %>

  </div>
  <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
    <h5>Image Details</h5>
    <table class="table">
      <tr>
        <td>Uploaded On</td>
        <td><%= @image.created_at.strftime("%m/%d/%Y") %> <%= @image.created_at.strftime("%I:%M%p") %></td>
      </tr>
      <tr>
        <td>Tags</td>
        <td>
           <% if @image.tags.count > 0 %>
            <% @image.tags.each do |tag| %>
                <% if tag.source == "Rekognition - Detect Labels"%>
                  <%= link_to tag.name, "/images/tag/#{tag.name}", :title => "#{tag.name} - #{number_to_percentage(tag.confidence)}", :class => "badge badge-secondary" %>
                <% end %>
                <% if tag.source == "Rekognition - Detect Moderation Labels"%>
                  <%= link_to tag.name, "/images/tag/#{tag.name}", :title => "#{tag.name} - #{number_to_percentage(tag.confidence)}", :class => "badge badge-success" %>
                <% end %>   
                  <% if tag.source == "Rekognition - Detect Text"%>
                  <%= link_to tag.name, "/images/tag/#{tag.name}", :title => "#{tag.name} - #{number_to_percentage(tag.confidence)}", :class => "badge badge-warning" %>
                <% end %>
                <% if tag.source == "Rekognition - Recognize Celebrities"%>
                  <%= link_to tag.name, "/images/tag/#{tag.name}", :title => "#{tag.name} - #{number_to_percentage(tag.confidence)}", :class => "badge badge-info" %>
                <% end %> 
                <% if tag.source == "Extract EXIF Data"%>
                  <%= link_to tag.name, "/images/tag/#{tag.name}", :title => "#{tag.name}", :class => "badge badge-dark" %>
                <% end %>                            
            <% end %>
          <% else %>
            <span class="badge badge-secondary">No Tags</span>
          <% end %>
        </td>
      </tr>
      <tr>
        <td>Analyzed By</td>
        <td>
          <span class="badge badge-secondary">Rekognition - Detect Labels</span>
          <span class="badge badge-success">Rekognition - Detect Moderation Labels</span>
          <span class="badge badge-warning">Rekognition - Detect Text</span>
          <span class="badge badge-info">Rekognition - Recognize Celebrities</span>
          <span class="badge badge-dark">Extract EXIF Data</span>
        </td>
      </tr>   
      <tr>
        <td>Favorited By</td>
        <td>
          <% if @image.favorites.count == 0 %>
            <span class="badge badge-secondary"> Nobody </span>
          <% else %>
            <% @image.favorites.each do |favorite| %>
            <span class="badge badge-secondary"> <%= favorite.user.username %> </span>
            <% end %>
          <% end %>
        </td>
      </tr>   
    </table>
  </div>
</div>

<!-- Recommendations 
<% if user_signed_in? %>
  <%= render_async useritem_recommendations_path do %>
    <i class='fa fa-spinner fa-spin'></i> Loading Recommendations ...
  <% end %>
<% end %>
-->

<!-- Comments -->
<div class="row">
  <div class="col-6">
    <h6>Comments</h6>
  </div>
  <% if current_user %>
  <div class="col-6">
    <%= link_to "Add Comment".html_safe, "#", :class => "btn btn-outline-primary pull-right", 'data-toggle' => 'modal', 'data-target' => '#commentModal' %>
  </div>
  <% end %>
</div>

<hr/>
<% if @image.comments.count == 0 %>
  <div class="row">
    <div class="col-12">
     No Comments
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-12">
       <% @image.comments.order(created_at: :desc).each do |comment| %>
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
            <span class="fa-stack text-muted">
              <i class="fa fa-circle fa-stack-2x"></i>
              <i class="fa fa-user fa-stack-1x fa-inverse"></i>
            </span>             
             <%= comment.user.username %>
            <span class="badge badge-secondary pull-right">
              <% if !comment.sentiment.nil? && !comment.sentiment.empty? %>
                  <% if comment.sentiment == "POSITIVE" %>
                    Positive
                  <% elsif comment.sentiment == "NEGATIVE" %>
                    Negative
                  <% elsif comment.sentiment == "NEUTRAL" %>
                    Neutral
                  <% elsif comment.sentiment == "MIXED" %>
                    Mixed
                  <% elsif comment.sentiment == "ERROR" %>
                    Error
                  <% else%>
                    <%= comment.sentiment %>
                  <% end%>
              <% end %>
            </span>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-10 col-sm-10 col-md-10 col-lg-11 col-xl-11 text-black-50">
            <p class="ml-5"><%= comment.comment %></p>
          </div>
          <div class="col-xs-2 col-sm-2 col-md-2 col-lg-1 col-xl-1">
            <% if can? :delete, comment %>
              <%= link_to '<i class="fa fa-trash"></i>'.html_safe, comment, method: :delete, data: { confirm: 'Are you sure?' }, :class => "pull-right" %>
            <% end %>
          </div>
        </div>
        <hr/>
      <% end %>
    </div>
  </div>
<% end %>

<% if current_user %>
<!-- Create Commment Modal -->
<div class="modal fade" id="commentModal" tabindex="-1" role="dialog" aria-labelledby="commentModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="commentModalLabel">Add Comment</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" id="comment-dismiss">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_for Comment.new do |f| %>
        <div class="modal-body text-center">
          <div class="row">
            <div class="col">
              <span><div id="comment-char-count" class="text-muted pull-right">0/500</div></span>
              <%= f.hidden_field :user_id, value: current_user.id %>
              <%= f.hidden_field :image_id, value: @image.id %>
              <%= f.hidden_field :sentiment, value: "Not Detected"%>
              <div class="form-group">
                <%= f.text_area :comment, :class => "form-control", :rows => "4", :id => 'comment-text' %>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal" id="comment-cancel">Cancel</button>
          <%= f.button "Comment".html_safe, :class => "btn btn-primary disabled", type: :submit, :id => "comment-submit", :disabled => true  %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>